-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGSMu3TmByD3WDZuQ
Qt1CQdyT1Ibddx1SzZ8FKgnzvPigCgYIKoZIzj0DAQehRANCAAT6iMxZv6nSVSOA
SHka26EfxwniVYzEamPCRf9amBt6gn9kPnlZzYmMp3/thpXO6sBeK0Mv3Wm9RoEo
E0jqqaqa
-----END PRIVATE KEY-----