default_platform(:ios)

platform :ios do
  desc "코코아팟 설치 → 테스트 → match → 빌드 및 TestFlight 업로드"

  lane :custom_release do
    # 2. 테스트 (실패해도 진행)
    scan(
      scheme: "BioLogTests",
      project: "BioLog.xcodeproj",
      fail_build: false,
      skip_build: true,
      clean: true,
      output_types: "html,junit",
      output_directory: "fastlane/test_output",
      build_for_testing: true
      # destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1"
    )



    # 3. 인증서 및 프로비저닝 프로파일 설치
    match(
      type: "appstore",
      readonly: true,
      git_url: "git@github.com:hyunwook13/match_repo.git"
      #clone_branch_directly: true
    )

    # 4. 빌드 및 업로드
    build_app(
      scheme: "BioLog"
    )

    pilot(
      api_key_path: "fastlane/api_key.json",
      ipa: "./BioLog.ipa"
    )
  end
end
