default_platform(:ios)

platform :ios do
  desc "코코아팟 설치 → 테스트 → match → 빌드 및 TestFlight 업로드"

  lane :custom_release do
    # 2. 테스트 (실패해도 진행)
    scan(
      scheme: "BioLogTests",
      project: "BioLog.xcodeproj",
      fail_build: false,
      skip_build: true,
      clean: true,
      output_types: "html,junit",
      output_directory: "fastlane/test_output",
      build_for_testing: true
      # destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1"
    )



    # 3. 인증서 및 프로비저닝 프로파일 설치
    match
#(
 #     type: "appstore",
  #    readonly: true,
   #   git_url: "git@github.com:hyunwook13/match_repo.git"
   #   #clone_branch_directly: true
   # )

  # 2) 키체인 언락 (CI 환경이면 꼭 필요)
  sh("security unlock-keychain -p \"#{ENV['MATCH_KEYCHAIN_PASSWORD']}\" ~/Library/Keychains/login.keychain-db")
  sh("security find-identity -v -p codesigning")

  # 3) App Store 서명 → IPA 생성
  #build_app(
  #  project:          "BioLog.xcodeproj",
  #  scheme:           "BioLog",
  #  export_method:    "app-store",
  #  output_directory: "build",
  #  output_name:      "BioLog.ipa"
  #)

    # 4. 빌드 및 업로드
    build_app(
      project: "BioLog.xcodeproj", 
      scheme: "BioLog",
      clean: true,
      silent: true,
      skip_package_pkg: true,
      export_method:    "app-store",
      output_directory: "build",
      output_name:      "BioLog.ipa",
      include_bitcode: false,
      export_options: {
          uploadBitcode: false,
          uploadSymbols: true,
          compileBitcode: false
      }
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["FASTLANE_APPLE_API_KEY_KEY_ID"],
      issuer_id: ENV["FASTLANE_APPLE_API_KEY_ISSUER_ID"],
      key_content: ENV["FASTLANE_APPLE_API_KEY_CONTENT"],
      is_key_content_base64: true
    )
    UI.message("🔑 api_key: #{api_key.inspect}")

    pilot(
      api_key: api_key,
      skip_waiting_for_build_processing: true,
      wait_processing_timeout_duration: 120,
      ipa: "build/BioLog.ipa"
    )
  end
end
